"""empty message

Revision ID: 6a97e022790b
Revises: 
Create Date: 2023-03-04 14:06:39.698202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a97e022790b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CounsellorType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('Gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gender')
    )
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=108), nullable=False),
    sa.Column('image', sa.String(length=60), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gender_id'], ['Gender.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('CounsellorTypeAssociation',
    sa.Column('counsellor_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['counsellor_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['CounsellorType.id'], )
    )
    op.create_table('Session',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('counsellor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['counsellor_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Session')
    op.drop_table('CounsellorTypeAssociation')
    op.drop_table('User')
    op.drop_table('Role')
    op.drop_table('Gender')
    op.drop_table('CounsellorType')
    # ### end Alembic commands ###
